name: Update News from MC & LiveMint

on:
  push:
    branches:
      - main  # Adjust the branch as needed
  schedule:
    - cron: '*/10 0-17 * * *'  

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      MONGO_DATABASE: ${{ vars.MONGO_DATABASE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Change directory and run script
        run: |
          cd news_scraper
          scrapy crawl scrape_mc
          scrapy crawl livemint_scraper
